
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA EQUALS ID KEYWORD LFLOWER NUMBER RFLOWER\n    declaration : KEYWORD LFLOWER list RFLOWER    \n    \n     list : exp COMMA list\n          | exp\n          |\n     \n    exp : ID EQUALS NUMBER\n        | ID \n    '
    
_lr_action_items = {'KEYWORD':([0,],[2,]),'$end':([1,7,],[0,-1,]),'LFLOWER':([2,],[3,]),'RFLOWER':([3,4,5,6,8,10,11,],[-4,7,-3,-6,-4,-2,-5,]),'ID':([3,8,],[6,6,]),'COMMA':([5,6,11,],[8,-6,-5,]),'EQUALS':([6,],[9,]),'NUMBER':([9,],[11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaration':([0,],[1,]),'list':([3,8,],[4,10,]),'exp':([3,8,],[5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaration","S'",1,None,None,None),
  ('declaration -> KEYWORD LFLOWER list RFLOWER','declaration',4,'p_declaration','parser.py',12),
  ('list -> exp COMMA list','list',3,'p_list','parser.py',20),
  ('list -> exp','list',1,'p_list','parser.py',21),
  ('list -> <empty>','list',0,'p_list','parser.py',22),
  ('exp -> ID EQUALS NUMBER','exp',3,'p_exp','parser.py',32),
  ('exp -> ID','exp',1,'p_exp','parser.py',33),
]
