
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLASSNAME EQUALS ID LEFTBRACE NEW RIGHTBRACE SEMICOLON\n    declaration : CLASSNAME ID EQUALS NEW CLASSNAME LEFTBRACE RIGHTBRACE SEMICOLON\n    '
    
_lr_action_items = {'CLASSNAME':([0,5,],[2,6,]),'$end':([1,9,],[0,-1,]),'ID':([2,],[3,]),'EQUALS':([3,],[4,]),'NEW':([4,],[5,]),'LEFTBRACE':([6,],[7,]),'RIGHTBRACE':([7,],[8,]),'SEMICOLON':([8,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaration':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaration","S'",1,None,None,None),
  ('declaration -> CLASSNAME ID EQUALS NEW CLASSNAME LEFTBRACE RIGHTBRACE SEMICOLON','declaration',8,'p_declaration','parser.py',8),
]
